OWNERS
Those OWNERs are from the community repository + lucperkins 👼
/cc @abayer @bobcatfish 
=> Add initial OWNER files

Makefile
=> Add a production-build target to deploy on netifly

content/en/docs/_index.md
Added _index.md back to `docs/` as required by Hugo.
review them:
- [N/A] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [N/A] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
=> Added _index.md to docs/

DEVELOPMENT.md, sync/sync.py
The DEVELOPMENT.md was very out of date! Also uncovered some difficult
to work with things along the way such as https://github.com/tektoncd/website/issues/38 which made it so that you need credentials to access the GCP bucket with
the background image in order to be able to run the sync script. I've
added a very hacky env var which lets one skip this until we tackle #38
review them:
=> Update DEVELOPMENT.md to describe netlify workflow

layouts/try/baseof.html
This tackles several issues:
* Until we get to #36 it removes the tutorials that we haven't audited
and updated
* It fixes #32 by adding the dashboard tutorial
* It fixes #29 by removing the placeholder links (and the link to the
google specific CI/CD docs which we can revisit later)
review them:
=> Replace other tutorials with dashboard tutorial

OWNERS
I would like to contribute to the automation side of things.
review them:
=> Add afrittoli as OWNER

OWNERS
I think I can help here and review other's changes...
=> Add skaegi as OWNER

sync/config/pipelines.yaml, sync/config/triggers.yaml
update the sync config for Pipelines and Triggersto use the "tektoncd" org instead of "michaelawyu"
review them:
=> Move default docs location to tektoncd master

Makefile
```
make serve
make sync serve
…
```
/cc @sbwsg @skaegi 
review them:
=> Split `serve` and sync and reuse-sync 🔍

sync/sync.py
/cc @skaegi @sbwsg @bobcatfish 
review them:
=> sync: remove unused imports 😛

Makefile
live-reload while hacking on the website :wink: 
/cc @sbwsg @skaegi 
review them:
=> serve: add --watch to live-rebuild

sync/README.md, sync/config/README.md, templates/README.md
Fix "all the little inconsistencies"
review them:
=> Fix sync.py doc to reference "sync" instead of "helper"

sync/sync.py
not yet supported by the sidebar, but at least it would sync correctly
/cc @skaegi @sbwsg 
review them:
=> sync: allow nested dirs 😅

sync/config/pipelines.yaml
Our sync script needs individual pages to be included
in its configuration for them to be synced to the website.
This PR adds the workspaces doc from the pipelines repo
so that it gets synced.
Depends on https://github.com/tektoncd/pipeline/pull/2315
=> Sync workspaces doc

content/en/docs/_index.md
=> Fixed a typo

layouts/partials/privacy-notice.html
Minor typo in the privacy notice pop up for the website. Change cookiies -> cookies. Also change your -> you. 
review them:
=> typo: change cookiies to cookies

content/en/docs/Getting Started/_index.md
Added a mention to use no.tags
review them:
=> Updated installation instructions for OpenShift

content/en/docs/Concepts/_index.md
A few more small typos in the Concepts section of the documentation.
Fixed the word exection -> execution in the documentation.
review them:
=> Fixed some typos in the Concepts section

asciinema/scenario.sh
Just a typo I noticed when checking out the project. The newline at the end is automatically added by 
Github web editor apparently, even if it didn't show for me when previewing changes :\
=> Fix typo in asciinema script

OWNERS
Closes #40
/cc @bobcatfish @skaegi 
review them:
=> Add sbwsg and AlanGreene as OWNERS 🎉

sync/config/cli.yaml
The initial `_index.md` file of CLI got added to the CLI repository,
so adding the cli repository to the sync script for the future.
/cc @skaegi @sbwsg 
review them:
=> Add CLI to sync 👼

content/en/docs/Dashboard/_index.md
Under the content/en/docs/Dashboard/_index.md page the url in the Important section was changed to have the correct url.
[Issue](https://github.com/tektoncd/website/issues/54)
review them:
=> Change the url for releases

content/en/docs/Dashboard/_index.md
=> fix dashboard doc links and port

content/en/docs/Concepts/_index.md
"compliation" should be "compilation".
review them:
=> Typo fixed

content/en/docs/_index.md
https://github.com/tektoncd/website/issues/44
Update the text to reflect the actual destination since we don't
currently have a try.tekton.dev subdomain.
review them:
=> Update clickable text pointing to 'Try' page

content/en/doc-con-content.md, content/en/doc-con-formatting.md, content/en/doc-con-main.md, content/en/doc-con-writing.md
Adds the Tekton Documentation Contributor's Guide and Style Guide.
This PR just adds the relevant files. I will link to those files from CONTRIBUTE.md and other places in the Tekton docs in a separate PR.
=> Add the Tekton Documentation Contributor's Guide and Style Guide.

content/en/doc-con-writing.md
Fixes more username formatting.
=> Fix more username formatting.

content/en/doc-con-main.md
=> Fix username formatting.

content/en/_index.html
Fixes a spelling error on the landing page
review them:
=> Fix spelling error

layouts/partials/footer.html, layouts/shortcodes/blocks/manifesto.html, layouts/shortcodes/blocks/partners-alternate.html, layouts/shortcodes/blocks/showcase.html
The banner for cd foundation and partners are off center after a certain size of 1739px. As a user this breaks the flow and decreases the usuability of the website. Reference: [#113](https://github.com/tektoncd/website/issues/113)
The padding for the banners on the tekton webpage had incorrect max-widths and some strange padding.
As a user these changes improve the flow of the website.
The copyright on the footer is not visible on IOS because rendering on IOS mobile devices are different and causes the style to overridden on IOS devices. Added the class to an one element below to fix this issue.
(Did not include images from IOS device)
(Did not include images from IOS device)
review them:
_See [the contribution …
=> Fix css from breaking for different browsers.

sync/config/pipelines.yaml
https://github.com/tektoncd/website/issues/125
- Migrating from v1alpha1 to v1beta1
- Pipeline metrics
- Variable substitution
review them:
=> Sync missing docs from pipeline repo

content/en/docs/Concepts/_index.md
Fix a few typos in Concepts/_index.md
Fix a few typos in Concepts/_index.md
review them:
=> A few typos in Concepts/_index

CONTRIBUTING.md
For new users who want to start contributing the main doc contributors guide is not easy to find.
review them:
=> Adding a resource to CONTRIBUTING.MD

content/en/doc-con-formatting.md
Adds guidance for formatting lists.
=> Add guidance for formatting lists.

katacoda.yaml
As per user guide https://www.katacoda.community/git-repository-structure.html#scenarios
add a katacoda.yaml so that we may store katacoda scenarios in a
dedicated folder in the website folder.
review them:
=> Add a katacoda.yaml to store tutorial in a folder

content/en/docs/Getting Started/_index.md, content/en/docs/Getting Started/pipelines.md
- Added a second task creation
- Added a pipeline example
- Added links back and forth from the page
Signed-off-by: JJ Asghar <jjasghar@gmail.com>
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
Co-authored-by: Paul Czarkowski <username.taken@gmail.com>
review them:
=> Added a Pipeline example to getting started

content/en/docs/Getting Started/pipelines.md
=> Fix pipeline-hello-goodbye.yaml

content/en/docs/Getting Started/pipelines.md
- Updates the goodbye world example so that it matches the hello world example and outputs the correct text
- Also updated the output from hello goodbye to goodbye world
=> Updated goodbye world example so that it matches the hello world example

content/en/docs/Getting Started/_index.md
=> Fix typo in _index.md

content/en/docs/getting-started-overview.md
Publishes a comprehensive overview of Tekton.
review them:
=> Publish an overview of Tekton

sync/config/pipelines.yaml
Add the events page to pipeline docs
review them:
=> Add the events page to pipeline docs

sync/config/cli.yaml, sync/config/pipelines.yaml, sync/config/triggers.yaml, sync/sync.py, sync/test_sync.py
Cleanup typos, simplify logic in a few places.
Make the list of files config a dict instead of a list of dicts.
review them:
/kind cleanup
=> Further cleanup the sync script

sync/README.md, sync/config/cli.yaml, sync/config/pipelines.yaml, sync/config/triggers.yaml, sync/requirements.txt, sync/sync.py, sync/test_sync.py, sync/test_versions.py, sync/versions.py
Add a new python script that can be used to add a new version to
the configuration of a component.
This script can be used by various projects as part of their
release process to keep the version on the website up-to-date.
review them:
/cc @popcor255 
/cc @AlanGreene
=> Add a script to add versions to sync configuration

sync/sync.py
Most of the time required for a sync is spent in two tasks:
- wget of all the original files
- validating the URLs with urlopen().read()
Running those two tasks in parallel greatly reduces the
processing time. This will be even more relevant when syncing
files from multiple releases.
review them:
=> Speed up things with parallel processing

sync/sync.py, sync/test_sync.py
The previous logic parses URLs with a regex first and then using
the markdown library. It then uses urlopen().read() to validate
links.
We use now the markdown library only to extract the list of links,
and then urlparse to deconstruct, analyse, adapt and reconstract
the link. We do not attempt to fetch links anymore, which means
that external links are not guaranteed to be working.
Absolute URLs are not changed (they may be external)
Fragments are relative to the page and do not need changes
Path only links should point to a file synced to the website
but sometimes the file may be missing (if it's not in the sync
configuration), so we follow this approach:
- prefix with base_path and check for the file locally
- if not found, prefix with base_url instead
Note that urlparse treats URLs …
=> Rewrite the link re-writing logic

OWNERS
I think it's safe to say that Napoleon has gone above and beyond
anything we could have asked for help on this repo.
Thanks for everything, and here's to more!
Signed-off-by: JJ Asghar <jjasghar@gmail.com>
=> Adding Napoleon as an owner

sync/config/pipelines.yaml
Pipeline release v0.17.3 which supercedes v0.17.2.
Updating the docs accordingly.
review them:
=> Replace pipelines v0.17.2 with v0.17.3

.gitignore
Instead of ignoring the whole content folder, only ignore folders
that we sync. Add a few more ignore files for python and IDEs.
review them:
=> Finetune .gitignore

Makefile, sync/config/pipelines.yaml, sync/config/triggers.yaml, sync/sync.py
Add the new version and add some docs that were previously excluded:
- deprecations
- runs
- tekton bundles contract
review them:
/cc @pritidesai @vdemeester @bobcatfish
=> Add docs for pipeline v0.18.0

content/en/docs/Overview/_index.md
Fixing the overview section markdown metadata so it is visually consistent with the other sections of the doc
review them:
/kind misc
=> Updating Overview section of Tekton

sync/config/pipelines.yaml
Switch pipeline docs from v0.18.0 to v0.18.1
review them:
=> Switch pipeline docs from v0.18.0 to v0.18.1

tutorials/katacoda/playground/background.sh
Update the Katacoda tutorial playground to the latest available releases:
- Pipelines 0.20
- Dashboard 0.13
- CLI 0.15
review them:
=> Update katacoda playground to latest releases

sync/README.md
Minor update to the docs of the versions script
review them:
=> Minor update to the docs of the versions script

sync/config/triggers.yaml
Add version v0.10.1 of triggers to docs
review them:
=> Add version v0.10.1 of triggers

sync/config/pipelines.yaml
Add pipeline v0.20.0 to the docs
review them:
=> Add pipeline v0.20.0 to the docs

content/en/docs/Overview/_index.md
Changing links to any reference to tektoncd/operator.
review them:
=> Renaming branches: handling operator repository

DEVELOPMENT.md
Add details about how to work with local repo caches.
review them:
=> Update the development.md

sync/config/cli.yaml
We missed some updates when releasing the cli, fixing this for current releases.
/cc @afrittoli
/cc @tektoncd/cli-maintainers 
review them:
=> Add missing CLI releases to the docs 📖

CONTRIBUTING.md
Changing links to any reference to tektoncd/community.
/hold
review them:
=> Renaming branches: handling community repository

content/en/doc-con-main.md, themes/docsy/layouts/partials/page-meta-links.html, tutorials/katacoda/getting-started/concepts.md, tutorials/katacoda/getting-started/intro.md, tutorials/katacoda/getting-started/src/tekton-katacoda/resources/git.yaml, tutorials/katacoda/runs/intro.md, tutorials/katacoda/tasks/intro.md
Changing links to any reference to tektoncd/website.
/hold
review them:
=> Renaming branches: handling website repository

roadmap.md
Creates a roadmap.md that describes the high-level roadmap for the website repo.
review them:
=> Create a Roadmap for the repo

sync/config/pipelines.yaml
Add pipelines v0.21.0
review them:
=> Add pipelines v0.21.0

content/en/docs/Overview/_index.md
Changing links to any reference to tektoncd/dashboard.
/hold
review them:
=> Renaming branches: handling dashboard repository

sync/config/README.md
Add sync documentation for configuring subdirectories.
Documents problem encountered in #250 
review them:
=> Add sync documentation for configuring subdirectories.

tutorials/katacoda/getting-started/tasks.md
Updated a sentence so that it reads a little bit better. Removed "as well" from the end. 
review them:
=> Updated sentence so that it reads a little bit better

content/en/docs/Overview/_index.md
Changing links to any reference to tektoncd/hub.
/hold
review them:
=> Renaming branches: handling hub repository

sync/config/pipelines.yaml
Updating the docs on the website with the latest Pipeline release - v0.22.0
review them:
=> Pipeline docs v0.22.0

sync/config/pipelines.yaml
Pipeline docs v0.23 and v0.24
review them:
=> Pipeline docs v0.23 and v0.24

content/en/docs/Getting Started/_index.md
Fedora 30-31 are no longer supported, updated info for releases currently available at [the copr repository](https://copr.fedorainfracloud.org/coprs/chmouel/tektoncd-cli/).
review them:
=> Updated copr info for current Fedora releases

sync/config/pipelines.yaml
- Updating from v0.24.1 to v0.24.3
- Adding v0.25.0
review them:
_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md) for more details._
=> Pipeline docs v0.24 and v0.25

sync/config/pipelines.yaml
Track release branches instead of tags in order to sync recent documentation updates.
Bump displayName to reflect the most recent patch release.
closes: #271
review them:
- [:no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Use branch refs in pipeline sync config

content/en/docs/Getting Started/pipelines.md
Fix an error in Getting started section of the documentation (wrong name of resource kind)
review them:
=> Fix kind of resource definition

content/en/docs/_index.md
* Improve the documentation landing page relates to issue #195
[statement] I could not add one or two proper images on landing page and leave it for other PR, and the other requirements done in this PR.
- change title from "Tekton Documentation" to "Welcome to Tekton"
- remove "What's next"
-  add a short blurb with a link to the tekton overview page where details all components completely(to keep clear separation between landing page and overview page content）
review them:
=> Improve the documentation landing page

sync/config/cli.yaml, sync/config/pipelines.yaml, sync/config/triggers.yaml
The documents were missing a few releases, I added them to the config
file.
The config file points to the release branch when available, otherwise
it uses the release tag.
review them:
- [x ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
=> Add missing Pipelines, Triggers and CLI versions

assets/js/anchor.js, layouts/partials/scripts.html
This PR adds anchor links next to section titles to solves an issue [#205](https://github.com/tektoncd/website/issues/205)
- assets/js/anchor.js added. Basically this file is same as docsy example project.
- layouts/partials/scripts.html modified so that the added js script works correctly.
review them:
=> Anchors to each section title in a document.

sync/config/triggers.yaml
Add the docs for triggers v0.17 and updated v0.16 to v0.16.1
review them:
- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Add triggers v0.17 and v0.16.1

.gitignore, netlify.toml
Add the netlify-plugin-checklinks plugin to check for broken
links on deploy.
review them:
- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Enable netlify-plugin-checklinks

sync/config/pipelines.yaml
Release v0.25.x branch has been created on pipeline side to add
documentation updates. Switch the config to the branch so that
we pull in any doc updates.
review them:
=> Point the pipeline config to release branch for v0.25

OWNERS
Thank you Geri for your contributions to the Docs WG!!
The community PR is merged https://github.com/tektoncd/community/pull/562
This one is to keep the OWNERS file in sync.
review them:
- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Add geriom to the OWNERS file

tutorials/katacoda/getting-started/src/tekton-katacoda/tasks/build.yaml, tutorials/katacoda/getting-started/tasks.md
Resolves https://github.com/tektoncd/website/issues/321
review them:
=> Pin python version in getting started tutorial

content/en/docs/Getting Started/_index.md
review them:
---
closes #305
closes #327
=> docs: update brew installation instruction

sync/config/results.yaml
Add sync config for tektoncd/results.
Currently only points at master, since there is no tagged release yet.
review them:
Fixes https://github.com/tektoncd/results/issues/28
=> Add sync config for tektoncd/results.

content/en/docs/Getting Started/_index.md
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
Point to nightly releases in GCS. Also fix some formatting (trailing whitespace)
Fixes #343 
review them:
=> Point to nightly releases instead of gcr.io

tutorials/katacoda/tasks/src/tekton-katacoda/tasks/task.yaml
For full consistency, have Katacoda scenario “Using Tekton Tasks” also pin the Python image used for the sidecar to version 3.9. Alternative approach to address https://github.com/tektoncd/website/issues/349.
review them:
- [ x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
=> Katacoda scenario Using Tekton Tasks - Also pin sidecar image

sync/config/triggers.yaml
Workadound for https://github.com/tektoncd/triggers/issues/1306 until
the fix is merged on triggers side.
review them:
=> Exclude triggers-api.md until front matter is added

content/en/docs/Getting Started/tasks.md
Replace `#!/bin/bash` with `#!/bin/sh` as alpine containers don't have bash.
review them:
- [x ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
(it is docs)
- [x ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
(I think it should be enough)
=> Fix example task

sync/config/pipelines.yaml
Updating the website configuration to include the two latest major releases - 0.34 and 0.35
review them:
=> adding two major releases

sync/config/triggers.yaml
Add the docs for triggers v0.18.0 & v0.19.0, and updated v0.17.0 to v0.17.1
review them:
=> Add triggers v0.17.1, v0.18.0 and v0.19.0

content/en/docs/Getting Started/_index.md
Include a series of introductory videos that can be very helpful for
many new users.
/closes #373 
[Docs staged preview](https://deploy-preview-378--tekton.netlify.app/docs/getting-started/)
review them:
=> Include Tekton videos in Getting Started

content/en/docs/_index.md
Resolves https://github.com/tektoncd/website/issues/381
review them:
=> Remove remaining reference to Try page on docs landing page

sync/config/cli.yaml
Resolves https://github.com/tektoncd/website/issues/369
review them:
=> Add missing CLI releases

sync/config/triggers.yaml
Add the docs for triggers v0.20.0
review them:
=> Add triggers v0.20.0

content/en/docs/How-to guides/_index.md, content/en/docs/How-to guides/clone-repository.md
Create a new section for how-to's. This section will include end-to-end
guides for common tasks. The first one is how to create a Pipeline to
clone a repository.
[Staged preview](https://deploy-preview-387--tekton.netlify.app/docs/how-to-guides/clone-repository/)
review them:
=> How to clone a git repo with Tekton

sync/config/dashboard.yaml
=> Add Dashboard v0.27 docs

content/en/docs/How-to guides/clone-repository.md, content/en/docs/How-to guides/kaniko-build-push.md
A tutorial that shows how to create a Tekton Pipeline to build and push
an image with Kaniko.
/closes [pipelines/4556](https://github.com/tektoncd/pipeline/issues/4556)
[Website Preview](https://deploy-preview-394--tekton.netlify.app/docs/how-to-guides/kaniko-build-push/)
review them:
=> How to build and push an image with Kaniko

layouts/shortcodes/blocks/cover.html, layouts/shortcodes/blocks/manifesto.html, layouts/shortcodes/blocks/partners-alternate.html
resolve https://github.com/tektoncd/website/issues/396
review them:
=> Accessibility add alt to images

sync/config/pipelines.yaml
Add v0.36 and v0.37 pipeline ref docs
review them:
=> Add v0.36 and v0.37 pipeline ref docs

assets/scss/_styles_project.scss
resolve https://github.com/tektoncd/website/issues/401
review them:
=> add more space to content on mobile (ui)

sync/config/pipelines.yaml
Adds config for latest pipeline release.
review them:
- n/a Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Add newest Pipelines release to sync configuration

content/en/docs/How-to guides/clone-repository.md, content/en/docs/How-to guides/kaniko-build-push.md
Fix typographical errors in the code samples.
review them:
=> Fix code typos

sync/config/pipelines.yaml
Updating website sync configuration to include the latest pipeline release - 0.39
review them:
=> updating configuration to include latest pipeline release

layouts/partials/footer.html
resolve https://github.com/tektoncd/website/issues/422
review them:
=> Accessibility update footer github link

sync/config/dashboard.yaml
=> Add Dashboard v0.29 docs

sync/config/triggers.yaml
Add the docs for Triggers v0.21.0
review them:
=> Add Triggers v0.21.0

sync/config/pipelines.yaml
Newest release 👼🏼 
review them:
=> Add release-v0.40.x to website

content/en/docs/Getting Started/tasks.md
https://github.com/tektoncd/website/issues/443
Tekton Pipelines currently does not install on Kubernetes 1.25 due to use of some deprecated resources that have been removed in that release. Pin the version used for the `minikube start` command so users following the tutorial have a working environment.
review them:
=> Pin Kubernetes version in getting started tutorial

layouts/partials/head.html, layouts/partials/scripts.html
Move jquery back to header
/closes #447 
review them:
=> Fix cookies modal not clossing

netlify.toml
resolve https://github.com/tektoncd/website/issues/441
review them:
=> update hugo to 0.104.0

Dockerfile, Makefile, docker-compose.yaml, layouts/partials/scripts.html, netlify.toml
This PR updates the site and Docker configurations to run on an environment closer to the Netlify production environment.
- The base image now runs ubuntu instead of alpine
- The container now serves the site via `netlify dev` instead of Instead of directly running `hugo serve`.
review them:
=> Update Docker to use Netlify and Ubuntu

go.mod, go.sum
Docsy update v0.3.0 => v0.4.0
review them:
=> Bump docsy version up to v0.4.0

content/en/docs/Concepts/_index.md, content/en/docs/How-to guides/_index.md, content/en/docs/Installation/_index.md, content/en/docs/Installation/local-installation.md, content/en/docs/Installation/pipelines.md, content/en/docs/Installation/triggers.md, content/en/docs/_index.md
To have a better docs user experience, this new section surfaces the installation documentation for all the Tekton components.
This first iteration adds Pipelines and Triggers, more work is required for other components' installation docs to be included here.
review them:
=> Create installation section

config.toml, content/en/docs/Contribute/doc-con-content.md, content/en/docs/Contribute/doc-con-formatting.md, content/en/docs/Contribute/doc-con-writing.md, content/en/docs/Contribute/run-locally.md, content/en/docs/Contribute/vendor-docs.md, content/en/vendor/README.md, content/en/vendor/disclaimer.md
- Add contribution guidelines for platform specific docs
- Simplify existing contribution guidelines
Implementation of the proposal outlined in #432 and discussed in the community meeting.
[Guidelines Preview](https://deploy-preview-452--tekton.netlify.app/docs/contribute/vendor-docs/)
review them:
=> Create vendor docs folder

assets/scss/_styles_project.scss, content/en/community/_index.md, layouts/community/list.html, layouts/partials/community-links.html
Community page with links to guidelines, communication channels and the community repository.
[Community page preview](https://deploy-preview-461--tekton.netlify.app/community/)
/closes #217  #448 
review them:
=> Create community page

content/en/vendor/README.md, go.mod, go.sum
Bump docsy version up and comment out jinja2 code in vendor guidelines.
Some highlights about this new Docsy version:
- Better styles for tabs
- Improved readfile shortcode rendering
- Consistent code block styles
review them:
=> Bump docsy version up to v0.5.1

sync/config/pipelines.yaml
Add pipeline v0.41.x
review them:
=> Add pipeline v0.41.x

sync/config/dashboard.yaml
=> Add Dashboard v0.30 docs

content/en/docs/Contribute/blog-guidelines.md
Create a new entry for blog posts in the contribution guidelines section.
review them:
=> Create blog contributions guidelines

assets/scss/_styles_project.scss, content/en/_index.html, content/en/docs/Getting Started/_index.md, content/en/docs/Getting Started/triggers.md, layouts/community/list.html, layouts/shortcodes/blocks/manifesto.html
Fix typos and small quality of life improvements:
- Typo in heading sentence in triggers getting started
- Update links on landing page
- Add scrolling and margin to version selector.
- Typo in community page, misson instead of mission
- Add vertical scrolling to extra-long code samples.
- Change RSS button styles to match other buttons styles.
- Code samples with vertical scroll bars:
- Version switcher with scroll bars and margin:
review them:
=> Fix typos and make small improvements

sync/config/pipelines.yaml
Updating the website configuration to include the latest pipeline release - v0.42.0
review them:
=> add pipeline v0.42

sync/config/triggers.yaml
Add the docs for Triggers v0.22.0
review them:
=> Add Triggers v0.22.0

content/en/docs/Getting Started/pipelines.md
Fix a simple grammatical mistake
review them:
=> Fix a minor typo

templates/version-switcher.js.template
Signed-off-by: BobDu <i@bobdu.cc>
fix lts docs href
review them:
=> fix lts version doc href

sync/config/dashboard.yaml
=> Add Dashboard v0.31 docs

layouts/shortcodes/blocks/manifesto.html
Mark Tekton as graduated from the CDF on the home page. Update the OpenSSF link to point to the correct section.
review them:
=> Mark Tekton as graduated on the homepage

content/en/docs/Getting Started/tasks.md
Fixed Spelling for Line -> "The process takes a few seconds, you see an output **symilar** ........." at [Getting-Started]( https://tekton.dev/docs/getting-started/tasks/#create-a-kubernetes-cluster )
=> quick fix for typo

sync/config/dashboard.yaml
Remove EOL releases
review them:
=> Add Dashboard v0.32 docs

sync/config/pipelines.yaml
review them:
- n/a Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
=> Add recent pipelines releases to sync config

sync/sync.py
Resolves https://github.com/tektoncd/website/issues/500
Resolves https://github.com/tektoncd/website/issues/499
Update the sync script to ensure both links and images are processed for URL rewrites.
/kind bug
review them:
=> Fix link rewrites

Makefile, analytics.txt
Add the recovery file required by the [Google Analytics recovery process](https://support.google.com/analytics/troubleshooter/7264014#ts=7271146). To revert this changes once the domain ownership is verified.
- First step to close #506 
review them:
=> Create file to recover analytics account

content/en/docs/How-to guides/clone-repository.md
Corrected a small typo in the "Clone a git repository with Tekton" guide.
review them:
=> Fix typo in the "Clone Repository" guide

sync/config/pipelines.yaml
Add the newly-released Pipeline v0.45.0 to the website sync config.
/kind misc
review them:
=> Add Pipeline v0.45.0 to website sync config

sync/config/dashboard.yaml
=> Add Dashboard v0.33 docs

content/en/docs/Contribute/doc-con-formatting.md, content/en/docs/Contribute/samples/pipeline1.yaml, content/en/docs/Contribute/samples/pipeline2.yaml, content/en/docs/Contribute/samples/task.yaml
Add instructions to embed code samples from external files in the documentation.
review them:
=> Add instructions to embed code samples in docs

Makefile, analytics.txt, config.yaml
- Delete recovery data.
- Replace old analytics ID with new one.
The old analytics account was no longer available and could not be recovered. The new analytics account uses [GA4](https://support.google.com/analytics/answer/10089681?hl=en), ownership is currently shared with @afrittoli; to be shared with the rest of the OWNERS once this is merged and we verify that everything works correctly.
review them:
/closes #506 
=> Add new analytics ID

sync/config/triggers.yaml
Add the docs for Triggers v0.23.0
review them:
=> Add Triggers v0.23.0

layouts/partials/head.html
Use the synchronous version of the analytics template. The asynchronous one is not compatible with GA4.
review them:
=> Update analytics template

content/en/blog/2022/graduation/index.md, content/en/blog/2023/cdcon-gitopscon/index.md
Fix typo in blog front matter likTitle -> linkTitle
review them:
=> Fix typo in blog front matter

sync/config/dashboard.yaml
Replace v0.34 which is now EOL
review them:
=> Add Dashboard v0.35 LTS docs

content/en/docs/Concepts/overview.md, content/en/docs/Concepts/supply-chain-security.md, content/en/docs/Getting-started/samples/build-push-run.yaml, content/en/docs/Getting-started/samples/build-push.yaml, content/en/docs/Getting-started/samples/provenance.json, content/en/docs/Getting-started/supply-chain-security.md, layouts/_default/_markup/render-codeblock-mermaid.html, layouts/partials/scripts.html
- High level overview of Software Supply Chain security.
- New introductory tutorial for Tekton Chains.
- Add chains to the list of component in the overview doc.
/closes #541 
- [Supply Chain Security overview](https://deploy-preview-530--tekton.netlify.app/docs/concepts/supply-chain-security/)
- [Getting Started tutorial](https://deploy-preview-530--tekton.netlify.app/docs/getting-started/supply-chain-security/)
review them:
=> Get started with chains

sync/config/pipelines.yaml
/kind misc
Add the new v0.48.0 release.
review them:
=> Update pipeline releases

sync/config/triggers.yaml
=> Add Triggers v0.24.0

layouts/partials/community-links.html
Fix invalid links in community links document.
Also minor formatting and typo fixed.
Fixes: https://github.com/tektoncd/community/issues/1016
review them:
=> Fix links in the community-links.html file

sync/config/dashboard.yaml
=> Add Dashboard v0.37.0 docs

sync/config/operator.yaml
=> Add Operator v0.67.0 to the website

sync/config/dashboard.yaml
=> Add Dashboard v0.38 LTS docs and remove EOL releases

sync/config/pipelines.yaml
=> Add Pipelines v0.50 LTS docs and remove EOL release

layouts/partials/community-links.html
Old link was broken:
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.
New one is from https://github.com/tektoncd/community/blob/main/contact.md#slack
review them:
=> Fix "Join the Tekton Slack!" link

content/en/docs/Getting-started/pipelines.md
The output shown is slightly different from the actual output seen when following the documentation.
Output text changed from `[hello : hello]` to `[hello : echo]`
review them:
=> Update pipelines.md to reflect actual observed pipeline output

sync/config/operator.yaml
* adds operator v0.68.x documentation
* updates displayName of v0.67.x
review them:
=> add operator v0.68.x docs

sync/config/dashboard.yaml
=> Add Dashboard v0.41 LTS docs and remove EOL releases

sync/config/pipelines.yaml
Add pipeline v0.54.0 release.
/kind misc
review them:
=> Update pipeline release v0.54.x

sync/config/operator.yaml
* adds operator release v0.69.x documentation
review them:
=> add operator release v0.69.x documents

DEVELOPMENT.md
Files:
- DEVELOPMENT.md
review them:
- [ x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
=> Updated DEVELOPMENT.md to specify required hugo version

.github/workflows/ruff.yml, sync/sync.py, sync/test_sync.py, sync/versions.py
Add the ruff python linter to the GitHub workflow and fix the errors it found.
review them:
=> Add python linter to GitHub workflow

sync/config/pipelines.yaml
=> Update pipeline release v0.56.x

sync/config/dashboard.yaml
Also remove v0.32.x LTS as it's EOL today.
review them:
=> Add Dashboard v0.43.x LTS docs

sync/config/operator.yaml
* adds operator v0.70.x documentation
review them:
=> add operator v0.70.x docs

sync/config/triggers.yaml
=> Add Triggers v0.26.1

sync/config/pipelines.yaml
=> Update pipeline release v0.57.x

content/en/docs/Getting-started/tasks.md
Added a missing 'to' and made the use of colons consistent when preceding command input or output
review them:
=> Added missing 'to' and consistent colons

sync/config/dashboard.yaml
=> Add Dashboard v0.45.x docs

sync/config/pipelines.yaml
=> Add Pipelines v0.58.x release

sync/config/triggers.yaml
=> Add Triggers v0.27.x  release

sync/config/pipelines.yaml
=> Add Pipelines v0.59.x  release

sync/config/pipelines.yaml
=> Remove EOL v0.47.x and v0.44.x releases for Pipelines

sync/config/pipelines.yaml
This commit updates the pipeline release v0.60.x 
review them:
=> Update pipeline release v0.60.x

sync/config/pipelines.yaml
This syncs the website.
review them:
/kind misc
=> Created Pipelines release for v0.61

sync/config/dashboard.yaml
=> Add Dashboard v0.48.0 docs

content/en/docs/Getting-started/tasks.md
Resolves https://github.com/tektoncd/website/issues/607
Minimum Kubernetes version is 1.28 since Pipelines v0.61.
Update the getting started docs to use the latest Kubernetes release.
review them:
=> Update kubernetes version in Pipelines getting started docs

sync/config/dashboard.yaml
=> Add Dashboard v0.49.0 docs and remove the EOL v0.38.0

sync/config/dashboard.yaml
=> Add Dashboard v0.50.0 docs

sync/config/operator.yaml
* adds operator `v0.73.x` documentation
* removes `v0.68.x` link - reached EOL
review them:
=> add operator v0.73.x docs

sync/config/dashboard.yaml
Also remove the EOL releases
review them:
=> Add Dashboard v0.52 docs

sync/config/operator.yaml
- adds operator v0.74.x documentation
review them:
=> add operator v0.74.0 docs

content/en/docs/Getting-started/supply-chain-security.md
Replaced `cosing` with `cosign`.
review them:
Partly compliant with commit message best practice guideline, but this is a microscopic change and I would assume the commit message is sufficient as is.
=> Update typo in supply-chain-security.md

layouts/partials/community-links.html
=> Update the slack invite to a link that does not expire

sync/config/dashboard.yaml
=> Add Dashboard v0.54.0 LTS docs and remove the EOL v0.43.0 LTS

assets/scss/_styles_project.scss, content/en/blog/2025/ghcr-migration/index.md, layouts/_default/baseof.html, layouts/docs/baseof.html, layouts/partials/banner.html
Adding a banner to the website was proposed and discussed in the Tekton Governing Board meeting from [March 26th](https://docs.google.com/document/d/1g2HQk_4ypYEWPX2WjOFa6vOMpwYoRNprph_P09TS1UM/edit?tab=t.0#heading=h.hjlmzvxw51o4).
Add blog entry with migration reason, details, what to do and links to the original mail from the Tekton Governing Board.
Add banner which is visible on the main site, the documentation and the community site. It is not visible on the blog site where the last blog entry is about the migration to ghcr.
Issue #645.
review them:
=> Add migration to Github Container Registry banner and blog entry

sync/config/dashboard.yaml
=> Add Dashboard v0.57.0 LTS docs and remove the EOL releases

content/en/blog/2025/ghcr-migration/index.md, content/en/blog/2025/tekton-pipeline-v1.0.0/index.md
This adds a blog entry about the recent 1.0 release of tektoncd/pipeline.
review them:
=> Add a blog entry about Tekton Pipelines 1.0

sync/config/dashboard.yaml
=> Add Dashboard v0.59.0 docs

sync/config/pipelines.yaml
Replace old version with supported LTS plus the latest v1.1.0
review them:
=> Update pipeline versions on the website

DEVELOPMENT.md, content/en/blog/2025/ghcr-migration/index.md
Add specific example where the changes should happen. Not only in the image of the deployment but also everywhere else an gcr image was previously used.
[See Slack conversation here.](https://tektoncd.slack.com/archives/C03KABYC7GD/p1752222861372069?thread_ts=1752182851.014979&cid=C03KABYC7GD)
Closes #659.
P.S.: Added a developer docs update saying that the specified versions are mandatory. I had a user last week who had issues running the website locally because he thought he can use the latest versions of the prerequisites. 
review them:
=> Update ghcr migration blog entry.

config.yaml
This PR is for https://github.com/tektoncd/website/issues/577
Updated the config.yaml file that is responsible for the template of website to include links to Slack Channel, Twitter and LinkedIn along with their respective icons.
In future, we will need to update the hugo version to update the twitter icon to new X as that would be the best approach.
review them:
- [ NA ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ Yes ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
_See [the contribution guide](https://github.com/tektoncd/website/blob/master/CONTRIBUTING.md …
=> Add Custom Icons for LinkedIn, Slack, and Twitter on Website #577

content/en/docs/Getting-started/pipelines.md, content/en/docs/Getting-started/samples/build-push.yaml, content/en/docs/Getting-started/samples/provenance.json, content/en/docs/Getting-started/supply-chain-security.md, content/en/docs/Getting-started/tasks.md, content/en/docs/Getting-started/triggers.md
Run through getting started, use latest API versions, container image versions, refresh outputs.
review them:
=> feat: refresh getting started

OWNERS
Add twoGiants as approver to website.
review them:
=> Add twoGiants as approver to website.

content/en/blog/2025/protect-signing-secrets-for-tekton-chains-using-confidential-computing/index.md
Image links in the latest blog post are broken, which is preventing deployment from happening.
review them:
=> Fix image links in blogpost

sync/config/dashboard.yaml
=> Add Dashboard v0.61.0 docs

.github/workflows/ruff.yml
https://github.com/tektoncd/plumbing/issues/2865
/kind misc
review them:
=> Pin actions by commit SHA
