- .github/issue-template.md
- .github/pull_request_template.md
- CONTRIBUTING.md
- DEVELOPMENT.md
- README.md
- code-of-conduct.md
With this commit we'll have the basic docs that are required for all
Tekton projects
(https://github.com/tektoncd/community/blob/master/process.md#project-requirements)
and a start at development + contributing guides, hopefully enough to
meet the requirements for #2 though we could still flesh these out
further.
Fixes #2
> Add basic Tekton docs 📝

- .gitignore
- sync/sync.py
Fixes #37 
(Still needs us to update the doc for Pipeline and Triggers to include front matter headers in comment)
Adds a "transform_links" function to sync.py so that "relative" *.md links are transformed into the format hugo expects.
Also add .gitignore entries for the Pipeline and Trigger content.
review them:
> Transform markdown links to hugo style

- content/en/docs/Getting Started/_index.md
As of Tekton Pipelines v0.11.0, a Kubernetes cluster version 1.15 or higher is required for Tekton. This pull request updates the documentation to make note of this.
review them:
> Update Kubernetes Version Information for Getting Started 

- content/en/docs/Getting Started/_index.md
Found two more instances of 
apiVersion: v1alpha1
in the Getting Started page. Updated those to use
apiVersion: v1beta1
In the Getting Started page, there were two more references to v1alpha1. Changed both.  Those are the only ones I could find.
review them:
> Changed some v1alpha1 in Getting Started

- content/en/docs/Getting Started/_index.md
This pull request adds more information on using `tkn` to start a `TaskRun` as opposed to making the user save a `TaskRun` ofd the website to a local file to start a `Task`. 
It would also be helpful to include a way for the user to not have to save the `Task` definition locally either to make it simpler to go through the tutorial (i.e. create the `Task` from a remote file using `kubectl apply -f`. Perhaps the `Task` definition can be stored in the website repo the link to it can be included in the documentation.
> Include tkn start in Getting Started Section and Remove Need to Save TaskRun to Local File

- sync/config/triggers.yaml
https://github.com/tektoncd/website/issues/81
The samples for the two 'Getting Started' links at the end of the main
Triggers page in the docs are missing so the links result in 404.
Add the YAML files to the sync config so they'll be included and available
from the links on the website.
review them:
> Add missing YAML files to Triggers sync config

- assets/js/launch-tutorial.js
The github link of Interactive Tutorial is https://github.com/undefined. 
It is incorrect. 
So does the qwiklabs link. 
Then fix them.
reference: [layouts/shortcodes/tutorial.html](https://github.com/tektoncd/website/blob/master/layouts/shortcodes/tutorial.html)
review them:
> fix the link of github and qwiklabs

- assets/scss/_styles_project.scss
- assets/scss/_variables_project.scss
- layouts/partials/privacy-notice.html
- layouts/shortcodes/blocks/cover.html
Privacy notice banner was offset and was not visible when site was docked to partial view. This allows a user to view the privacy notice properly.
Add styling to tekton banner hero logo.
The banner hero logo would break the website flow because of the css. Changed the css to fix this issue. Added var to scss to increase readability. These changes increase responsiveness.
Before:
After:
review them:
> Fix Website Responsiveness

- config.toml
- themes/docsy/layouts/partials/page-meta-links.html
https://github.com/tektoncd/website/issues/65
It's possible to define page-level params in each project repo that cascade to all child pages. We could use this to make project-specific config available in our templates without having to duplicate it on each page.
For example, taking the Triggers project, adding something like this to the README.me (renamed to _index.md on the website):
```diff
---
title: "Triggers"
linkTitle: "Triggers"
weight: 4
description: >
Event Triggers
+cascade:
+  github_project_repo: https://github.com/tektoncd/triggers
---
```
This allows us to point the 'Edit this page' and 'Create documentation issue' links to the correct location. If this `github_project_repo` param is not present, it falls back to existing behaviour so that content from the website repo …
> Update 'Edit this page' link to point to correct project repo

- OWNERS
This PR removes me from OWNERS file.
It made sense for me to be in OWNERS while we were releasing Beta but I'm not keeping up with current website planning & work so don't want to be blocking reviews.
> Remove sbwsg from OWNERS

- DEVELOPMENT.md
- Makefile
It is not straight forward on how to run the dev environment. You can not run the website locally without running npm, the sync script and hugo in a specific order. I do not believe this is documentation anywhere and was mention in this issue. https://github.com/tektoncd/website/issues/3
I added instructions on to run the tekton website dev environment.
review them:
> Add steps to docs for running website dev envrioment locally

- sync/config/triggers.yaml
Some of the Triggers content was moved in https://github.com/tektoncd/triggers/pull/642,
specifically: create-ingress.yaml and create-webhook.yaml
These have been moved to the getting-started folder which broke
the website sync script, blocking other changes. This can be seen
in the failing `netlify/tekton/deploy-preview` check on PRs.
Update the sync config to point to the new paths to unblock
other changes.
review them:
> Fix path to Triggers yaml files in sync config

- config.toml
- content/en/_index.html
- content/en/docs/Concepts/_index.md
- content/en/docs/_index.md
Tekton is a cloud native project, not necessarily a kubernetes native
project, and in fact (beyond basing our design around k8s style
resources and using k8s containers) we try to minimize our coupling to
k8s (at least in our API).
If you look at our README you can see that we are k8s-style and cloud
native: https://github.com/tektoncd/pipeline#-tekton-pipelines
You can see this reflected in our mission as well:
"Be the industry-standard, cloud-native CI/CD platform components and
ecosystem."
https://github.com/tektoncd/community/blob/master/roadmap.md#mission-and-vision
This commit updates the wording to be a bit more accurate.
review them:
_See [the contribution …
> Change "kubernetes native" to "cloud native" ☁️

- content/en/docs/Getting Started/_index.md
With tekton pipeline installed, cm `config-artifact-pvc` (and more) is created automatically. Running below command to will fail with `Error from server (AlreadyExists): configmaps "config-artifact-pvc" already exists`.
```
kubectl create configmap config-artifact-pvc \
--from-literal=size=10Gi \
--from-literal=storageClassName=manual \
-o yaml -n tekton-pipelines | kubectl replace -f -
```
With `--dry-run=client`, it works.
review them:
> add --dry-run option to command

- tutorials/katacoda/playground/assets/wait.sh
- tutorials/katacoda/playground/background.sh
- tutorials/katacoda/playground/finish.md
- tutorials/katacoda/playground/foreground.sh
- tutorials/katacoda/playground/index.json
- tutorials/katacoda/playground/intro.md
- tutorials/katacoda/playground/step1.md
Add a Katacoda scenario that can act as a playground for users
to experiment with Tekton in a sandbox environment.
This environment provides a 2-node Kubernetes cluster with the
following projects installed:
- Pipelines v0.14.3
- Dashboard v0.8.2
- CLI v0.11.0
Typical startup time is <1minute, but may take 2 or 3 minutes
in some cases. The installation should not require any manual
steps by the user.
I currently have this deployed at https://katacoda.com/alangreene-tektoncd/scenarios/playground for testing.
review them:
> Add Katacoda playground

- content/en/docs/Getting Started/_index.md
Instead, assume a cluster already exists, or briefly document using
`kind` to set up a local cluster for testing.
Rationale for this change (first in a series) is outlined in this doc (shared with tekton-dev@): https://docs.google.com/document/d/1sMt06g40Jt0Pr5g0Rgfe02az1A9FAFme8mf962UuSEQ/edit
review them:
- [y] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [y] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
/cc @sergetron 
/cc @AlanGreene 
/cc …
> Remove vendor-specific cluster setup instructions

- layouts/partials/navbar-version-selector-docs.html
- templates/version-switcher.js.template
The version switcher dropdown box mentiones releases, however currently
it refers to "master" which is not a release at all. I think we could
use the wording "version" which is more generic.
Archived versions instead is a link to releases on github. Changing the
wording accordingly.
review them:
> Change from releases to versions

- sync/sync.py
- sync/test_sync.py
For relative URLs that are not matched to a file on disk, we
rewrite them to a github URL. The base URL is joined to the
path with urljoin. If the the path includes a `..` then
urljoin goes up one level from the last `/` in the base URL.
Because of that, we need the base url to end with a `/`.
Added tests to avoid this from breaking in future.
Fixes #186
Fixes #177
review them:
/kind misc
> Use a trailing slash for the rewrite URL

- sync/sync.py
- sync/test_sync.py
- sync/test_versions.py
Hugo produces lowercase anchors into rendered markdown pages.
If a fragment points to a markdown page, make it lower case.
We do not touch fragments on external URLs or on github files
that are not markdown.
Fixes #159
review them:
/kind bug
> Lowercase fragments on local markdown pages

- .github/workflows/nightly-deploy.yml
Use a simple scheduled github action to deploy
the website nightly. The deploy step includes sync,
so this will pull in an up to date version of the docs
on the master branch.
review them:
> Add a nightly deployment for the website

- sync/README.md
- sync/requirements.txt
- sync/sync.py
- sync/test_sync.py
- sync/test_versions.py
- sync/versions.py
We may need to remove versions: when releasing a minor version
we might want to remove previous releases on the same major version.
Adding a version rm command for that.
As part of the process, move away from absl-py and use click instead
that helps handling different commands.
review them:
/kind feature
> Add a version rm command to versions

- .gitignore
- sync/README.md
- sync/config/README.md
- sync/config/cli.yaml
- sync/config/pipelines.yaml
- sync/config/triggers.yaml
- sync/requirements.txt
- sync/sync.py
- sync/test_sync.py
- sync/test_versions.py
- sync/versions.py
Change the sync configuration from files to folders, so make the
configuration easier to maintain as well to allow syncing folders
of generated docs, where the list of files may vary and for which
it is not possible to pre-add the YAML headers used by docsy.
This change implies the following modification to the sync process:
- we do not download files one-by-one to disk and rewrite them to
a different location on disk. Instead we git clone all relevant
repositories, and pull files at the correct reference into the
site content folder direcly
- we now support pulling content from different folders in the
tekton repos. As part of the configuration a target folder in
the website can be specified. The default is ''.
This will allow pulling in content from other folders that may
not even be …
> Switch sync config from files to folders

- sync/sync.py
- sync/test_sync.py
In case of non-md files in nested folders, the filename used in the
rewrite included the target path leading to double-path in the link.
Fixed that and added a use case for the non-md file in a subfolder.
review them:
/kind bug
> Fix the case of non-md files in nested folders

- sync/sync.py
There is a chance that utf-8 encoded text may be decoded
successfully but wrongly as ascii. UTF-8 instead should always be
able to decode ascii successfully, so let's try UTF-8 first.
Fixes: #211
review them:
/kind bug
> Try utf-8 first when decoding text

- Makefile
- netlify.toml
The baseURL is not set for dev and prod which causes the following
issues:
- for dev, the URL shown on the console is not the correct one
- for prod, the generated sitemap.xml uses relative URLs, which
makes it not parsable by the search engine
This is already setup correctly for deploy-previews.
Partially fixes #191
review them:
/cc @vdemeester
> Fix the baseURL for dev and prod use caes

- netlify.toml
The website header partial sets the meta index, follow if the
HUGO_ENV is set to production, and no index no follow otherwise.
Change the HUGO_ENV to be production for the production environment.
Related to #191
review them:
/cc @vdemeester @AlanGreene
> Enable index, follow in the production website

- tutorials/katacoda/getting-started/concepts.md
This PR fixes a broken link to an image of an architecture diagram.
Closes: #246
Signed-off-by: Steve Martinelli <s.martinelli@gmail.com>
> fix broken link in getting-started tutorial

- sync/requirements.txt
- sync/sync.py
- sync/test_sync.py
When replacing links, we parse the markdown document line by line. When
the markdown parsers encounters an indented line, without the context of
the surrounding lines, it assumes a code block and does not render the
links to html, which means we do not re-write those links.
This patch fixes the issue by stripping left spaces in the text
fragments sent to "get_links", so that we can extract links successfully
and preserve the spaces in the rendered markdown.
Fixes: #229
review them:
/kind bug
/cc @AlanGreene
> Fix broken links in lists and indented text

- content/en/docs/Getting Started/_index.md
"apt" is used to install packages on deb-based distros, not "rpm", which is used on rpm-based distros.
"apt" is not able to install individual packages from a URL; the package has to be downloaded prior to be
installed. curl (instead of wget) is used as it is the tool used later in the same page to get the LINK-TO-TARBALL.
review them:
> Fix install instructions for deb-based distros

- content/en/docs/Overview/_index.md
- sync/config/cli.yaml
- sync/config/triggers.yaml
Changing links to any reference to tektoncd/triggers.
/hold
review them:
> Renaming branches: handling triggers and CLI repository

- content/en/docs/Getting Started/_index.md
- content/en/docs/Overview/_index.md
- sync/config/pipelines.yaml
- tutorials/katacoda/dashboard/step1.md
- tutorials/katacoda/playground/step1.md
Changing links to any reference to tektoncd/pipeline.
/hold
review them:
> Renaming branches: handling pipeline repository

- sync/config/triggers.yaml
The website lists v0.10.1 as the latest release of triggers. This PR adds v0.11.2, v0.12.1, v0.13.0 to the sync config.
review them:
> Add triggers v0.11.2, v0.12.1, v0.13.0 and v0.14.1

- content/en/docs/Concepts/_index.md
- content/en/docs/Getting Started/_index.md
- content/en/docs/Getting Started/pipelines.md
- tutorials/katacoda/basic-pipeline/step2.md
Signed-off-by: shaowenchen <mail@chenshaowen.com>
https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/ is modified to https://kubernetes.io/docs/concepts/workloads/pods/
review them:
> fix broken links about Kubernetes pod

- sync/sync.py
Was working with @geriom to get this running on his ubuntu machine -
when run on a ubuntu machine (still not sure why netflify isnt havign
the same issue), the script fails with errors such as:
```
ERROR:root:Cannot process text/markdown file docs/logs.md
```
I reproduced this by running an `ubuntu` docker container and
following along with [the DEVELOPMENT.md](https://github.com/tektoncd/website/blob/main/DEVELOPMENT.md)
and go the same errors! It seems that when I run on my mac, the mime
type of each file is `text/plain` and when I run on ubuntu the mimetype
is `text/markdown`. I'm not sure WHY this difference is happening (e.g.
the installed `gitpython` versions were the same) but since
`text/markdown` seems like a valid type for markdown files, maybe we can
just support both!
These …
> Fix mime type detection when running on ubuntu 🔎

- tutorials/katacoda/basic-pipeline/init.sh
- tutorials/katacoda/basic-pipeline/step1.md
- tutorials/katacoda/dashboard/step1.md
- tutorials/katacoda/getting-started/resources.md
- tutorials/katacoda/getting-started/setup.md
- tutorials/katacoda/playground/background.sh
- tutorials/katacoda/runs/init.sh
- tutorials/katacoda/runs/io.md
- tutorials/katacoda/runs/src/tekton-katacoda/pipelineResources/git.yaml
- tutorials/katacoda/tasks/init.sh
- tutorials/katacoda/tasks/io.md
- tutorials/katacoda/tasks/src/tekton-katacoda/pipelineResources/git.yaml
https://github.com/tektoncd/website/issues/290
The Kubernetes environment provided by Katacoda is version 1.18. Tekton Pipelines
releases from v0.27 require a minimum of Kubernetes 1.19. Since the tutorials
currently install the 'latest' release this means they are broken.
Pin the Pipelines release version to v0.26 since this is last release that supports
Kubernetes 1.18. In future we may need to adopt a different approach to building
these tutorial environments so we have more flexibility on the Kubernetes version.
Deployed these changes to a test Katacoda profile: https://katacoda.com/alangreene-tektoncd
review them: …
> Pin Pipelines version in Katacoda tutorials for compatibility with k8s 1.18

- DEVELOPMENT.md
sync/sync.py fails if the installed git version is older than 1.8.5.
That is because sync/sync.py calls git command with -C option internally, and the option was
introduced at git 1.8.5. 1.8.5 is quite old but the default git version is older than it in certain
Linux distribution. Adding git version prerequisite could be more developer-friendly.
review them:
> Add git version prerequisite to DEVELOPMENT.md.

- layouts/shortcodes/tutorial.html
Delete dangling div tag in the tutorial shortcode code that causes the
footer to not render correctly in some pages.
> Delete unnecessary closing tag

- sync/README.md
- sync/config/operator.yaml
- sync/config/pipelines.yaml
- sync/config/triggers.yaml
- sync/sync.py
- sync/test_sync.py
We used to check for reference names in the sync script, which required
the branch name to be configured as "origin/<branch-name>".
This approach broke some of the links.
Fix the sync script by looking for remote ref names in the python git
wrapper, and changing all config to use branch name only.
Fixes #313
review them:
> Match the remote ref names when looking for branches

- config.toml
Hugo supports markdown emojis in the :<name>: format by they are
disabled by default. Enable them as might be used in Tekton docs.
Fixes #268
review them:
- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
> Enable emoji for hugo

- sync/README.md
- sync/config/README.md
- sync/config/cli.yaml
- sync/config/operator.yaml
- sync/config/pipelines.yaml
- sync/config/triggers.yaml
- sync/sync.py
- sync/test_sync.py
- sync/test_versions.py
displayOrder and docDirectory are not used anymore by the sync
script, so remove them from config, docs and tests.
The default target is now "" and not "/" anymore, so fix a few
comments where it referred to the old value.
Fixes: #323 312
review them:
> Cleanup unused configs in sync.py

- .gitignore
- sync/config/chains.yaml
- sync/sync.py
Add configuration for chain docs.
Front matter is missing so adding some basic one just to test the
PR. The docs include images at least one image (the logo) which
does not work as the only mime type supported for in-repo data is
text / markdown - which is something we need to fix in the sync
script.
This also adds support for using "." to get documents from the
repo root.
review them:
> Add config for chains

- tutorials/katacoda/tasks/builders.md
- tutorials/katacoda/tasks/src/tekton-katacoda/tasks/task.yaml
Fix Katacoda scenario Using Tekton Tasks: https://github.com/tektoncd/website/issues/347
The version of `pytest` specified in `dev_requirements.txt` is incompatible with Python 3.10. This remedy uses a fixed container image version for Python. In order to make the Katacoda experience as reproducible as possible, it’s a good practice to use fixed versions for as many things as possible anyway.
review them:
> Fix Katacoda scenario Using Tekton Tasks

- tutorials/katacoda/basic-pipeline/step1.md
- tutorials/katacoda/basic-pipeline/step2.md
- tutorials/katacoda/basic-pipeline/step3.md
https://github.com/tektoncd/website/issues/352
Some textual improvements for Katacoda scenario “Tekton Basic Pipeline”. Fixed a typo and changed the YAML that we are instructed to copy to match the “reference” output shown in steps 1 and 2. Accordingly, changed the “reference” output shown in step 3 to match.
The rationale is that the output is now what one would expect in the first place (and becomes 100% predictable; with the script being echoed to the output, the order of that and the actual output of the `echo` command would differ between executions).
review them:
> Issue 352 - Katacoda scenario Tekton Basic Pipeline - Textual improvements

- sync/config/pipelines.yaml
Pipeline v0.33.0 was released today.
Add the docs for the last four versions of pipeline - it was not updated
since v0.29.x.
Using v0.33.x as display name so that we don't need to update the sync
config on minor releases.
review them:
> Add the last four pipeline releases

- sync/requirements.txt
The current version of Jinja2 cases issues with the transitive
dependency markupsafe. Updating to a recent version fixes the
issue.
review them:
> Update the version of Jinja2

- netlify.toml
Currently the netlify deploy uses hugo v0.53, which is almost 4 years
old and has some big inconsistencies when rendering markdown. This bumps
hugo up to the latest release, v0.94.2
review them:
> Update hugo version

- netlify.toml
Update the dev section as recommended by `netlify dev` to avoid
the framework selection prompt on startup. Without this the command
hangs waiting for user input. See output from netlify CLI that
suggested the change:
```
$ netlify dev
◈ Netlify Dev ◈
◈ Injected netlify.toml file env var: HUGO_VERSION
◈ Ignored general context env var: LANG (defined in process)
◈ Ignored general context env var: LC_ALL (defined in process)
? Multiple possible start commands found Hugo-hugo server -w
Add 'framework = "hugo"' to the [dev] section of your netlify.toml to avoid this selection prompt next time
◈ Starting Netlify Dev with Hugo
hugo server \
--baseURL http://localhost:8888/ \
--buildDrafts \
--buildFuture \
--disableFastRender \
--ignoreCache \
--watch
```
These are the criteria that every PR …
> Update netlify dev to avoid framework prompt

- content/en/docs/Getting Started/pipelines.md
- content/en/docs/Getting Started/tasks.md
Based on feedback:
-  Explicitly mentions in the installation instructions that `tkn` is the
command name of the Tekton CLI.
-  Provide a better description of when the installation of Tekton
Pipelines is complete. Namely, when both tekton-pipelines-controller
and tekton-pipelines-webhook are `Ready`. Added output example.
-  Consistent capitalization of "Task", "TaskRun", "Pipeline",
"PipelineRun", "Workspace", and "Step". Since these are first class
objects with a specific meaning within Tekton, we treat them
as nouns when writing docs.
review them:
> Editorial review

- content/en/docs/How-to guides/kaniko-build-push.md
Recently, the git-clone task was updated to version 0.8 which is not
backwards compatible in that it is run as a non-root user which does not
have access to volumes mounted via workspaces by default. To accomodate
this change, the users need to update their PipelineRuns and TaskRuns
with `podTemplate.securityContext.fsGroup = 65532` to fix the
permissions on mounted volumes.
This commit makes this configuration change in the how-to guide.
review them:
> Update git-clone task instructions per 0.8

- sync/sync.py
- sync/test_sync.py
Commenting out the front matter allows to reuse that content in other
files where it may be relevant using the `readfile` shortcode. This
doesn't affect the normal functionality of the YAML front matter.
review them:
> Comment out synced files front matter

- content/en/docs/How-to guides/clone-repository.md
- content/en/docs/How-to guides/kaniko-build-push.md
To avoid having to delete and reapply a Pipelinerun when developing your code, this PR switches to `generateName`, which adds a suffix to have a unique name each time.
Additionally, this PR also fixes a problem with the latest version of the `git-clone` Task in the Git clone tutorial.
review them:
> Use generateName in pipelineruns

- assets/js/click-to-copy.js
- assets/scss/_styles_project.scss
- layouts/partials/head.html
- layouts/partials/scripts.html
Implement click-to-copy for code blocks. Code blocks with no syntax highlight won't show the button, useful to show command outputs that are not supposed to have syntax highlighting and don't need to be copied.
Additional changes:
- Bump up Popper and Bootstrap versions
- Move script-importing code from header to the scripts partial
| Normal view | Mouseover | Clicked |
| ----------------- | :-------------: | ---------- |
| ![Screenshot from 2022-09-21 10-03-36](https://user-images.githubusercontent.com/22261639/191526145-61d041fe-6bc5-4c0c-b45a-32a13641c40a.png) | ![Screenshot from 2022-09-21 10-03-44](https://user-images.githubusercontent.com/22261639/191526227-e5f078be-2ec3-4205-95b2-783dac5f3710.png) | ![Screenshot from 2022-09-21 …
> Implement click-to-copy for code listings

- content/en/docs/How-to guides/kaniko-build-push.md
Fixing a small typo which breaks the How-to Guide if followed blindly/copy-pasted.
The documentation refers to `pipeline,yaml` in line 49, but I believe it should be referring to `pipeline.yaml` ( using a punctuation instead of a comma ).
```diff
- Create a new Pipeline, `pipeline,yaml`, that uses the *git clone* Task to [clone
+ Create a new Pipeline, `pipeline.yaml`, that uses the *git clone* Task to [clone
```
review them:
> Fix typo in kaniko-build-push.md

- content/en/docs/Getting Started/triggers.md
https://tekton.dev/docs/getting-started/triggers/#:~:text=tekton%2Dpipelines%20%2D%2Dwatch-,When%20tekton%2Dtriggers%2Dcontroller%2C%20tekton%2Dtriggers%2Dwebhook%2C%20and%20tekton%2Dtriggers%2Dcore%2Dcontroller%20show%201/1%20under%20the%20READY%20column%2C%20you%20are%20ready%20to%20continue.%20For%20example%3A,-NAME%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20READY%20%20%20STATUS
change "tekton-triggers-core-controller" to "tekton-triggers-core-interceptors"
review them:
> wrong component name in docs

- sync/config/cli.yaml
As of now the latest version of CLI displayed is v0.23.1 whereas the latest current release is v0.28.0. Updating the sync/config/cli.yaml with the latest releases that were done post v0.23.1
Signed-off-by: vinamra28 <jvinamra776@gmail.com>
review them:
> Sync TektonCD CLI releases

- .gitignore
- assets/scss/_styles_project.scss
- config.yaml
- content/en/docs/Installation/pipelines.md
- layouts/docs/baseof.html
- layouts/partials/release-selector.html
- sync/config/pipelines.yaml
- sync/sync.py
- templates/release-switcher.js.template
- Create new partial to display links to the Nightly (repo HEAD) and Latest LTS releases. As discussed on [Slack](https://tektoncd.slack.com/archives/CLCCEBUMU/p1675871079501169).
- Disable breadcrumb and use that space for the links. I'm trying to keep top of the doc uncluttered, I think the site is fairly flat, the left nav tree provides enough context to figure out your current location. Open to alternative suggestions.
- Fix delimiter in Pipelines Installation docs `readfile`.
|  **Preview with Nightly and LTS** |
| --- |
| ![Screenshot from 2023-02-23 13-46-45](https://user-images.githubusercontent.com/22261639/221014826-f260a18e-b2da-4c38-8b68-17b7c6693714.png) |
| **Preview with only Latest**  |
| ![Screenshot from 2023-02-23 …
> Add release selector to docs

- content/en/docs/How-to-guides/clone-repository.md
show-readme.yaml file contains description which causes following error since description under metadata is an unknown field, removing that line fixed the issue.
Failure:
```
kubectl apply -f show-readme.yaml
Error from server (BadRequest): error when creating "show-readme.yaml": Task in version "v1beta1" cannot be handled as a Task: strict decoding error: unknown field "metadata.description"
```
Success:
```
kubectl apply -f show-readme.yaml
task.tekton.dev/show-readme created
```
review them:
> Remove metadata.description from show-readme.yaml

- sync/config/pipelines.yaml
Add the new v0.47.0 LTS release.
Remove EOL release v0.46.0 and v0.43.0.
review them:
> Update pipeline releases

- .gitignore
- public/_redirects
This sets up a [redirect](https://docs.netlify.com/routing/redirects/#syntax-for-the-redirects-file) so for /predicate/chains to Chains documentation. 
i.e. `https://tekton.dev/predicate/chains/slsa/v2` -> `https://github.com/tektoncd/chains/tree/main/docs/predicate/slsa/v2`
(these pages don't actually exist yet).
This is a placeholder for SLSA predicate type documentation. We may try to figure out how to handle these better with the doc import process later on, but we need these to keep URL structure that AFAIK sync.py doesn't support well today. These URLs show up in Chains-generated SLSA predicates. 
We do not need navigation for these URLs (we'll figure out if we want to add this later with the doc syncing).
See https://github.com/tektoncd/chains/pull/906 for more details.
Fixes #561 …
> Redirect /predicate/chains to Chains documentation.

- content/en/docs/Getting-started/tasks.md
- Bump the kubernetes version for [minimum (v1.25)](https://github.com/tektoncd/pipeline/releases) and [latest release on v1.25](https://kubernetes.io/releases/#release-v1-25)
```
$ minikube start --kubernetes-version v1.24.4 --driver docker
$ kubectl apply --filename \
https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
$ kubectl get pods --namespace tekton-pipelines --watch
NAME                                           READY   STATUS              RESTARTS      AGE
tekton-events-controller-77f545999b-8ptt4      0/1     ContainerCreating   0             82s
tekton-pipelines-controller-5886b486bd-n2lb7   0/1     CrashLoopBackOff    1 (18s ago)   82s
tekton-pipelines-webhook-846fd9b64d-ngtj9      0/1     ContainerCreating   0             82s …
```
> Update tasks.md for bumping kubernetes version to minimum requirement.

- layouts/partials/community-links.html
Resolves https://github.com/tektoncd/website/issues/568
The previous Slack invite link has expired, and was replaced in the community repo with a new link set not to expire. Update the community links page on the website to use the new link.
URL taken from https://github.com/tektoncd/community/pull/1094
review them:
> Update Slack invite link

- layouts/partials/scripts.html
Related https://github.com/tektoncd/results/pull/708
/kind misc
review them:
> Update mermaid to fix Results data model diagram

- sync/config/dashboard.yaml
> Add Dashboard v0.46 LTS and v0.47 docs and remove EOL releases

- sync/config/operator.yaml
* adds operator v0.71.x documentation
* marked `LTS` releases
review them:
> add operator v0.71.x docs

- content/en/docs/Getting-started/tasks.md
When creating a task, the text says that the output confirms that the task completed successfully, while the task did not run yet as a TaskRun object was not created yet.
Changing the text so it imply that the task resource was created instead.
review them:
> Minor rewording in tasks.md

- DEVELOPMENT.md
- package.json
Following the ["Running Natively" guide](https://github.com/tektoncd/website/blob/main/DEVELOPMENT.md#running-natively) in the development docs does not work anymore because the [`netlify-cli` needs Node v18 or above](https://github.com/netlify/cli?tab=readme-ov-file#installation). The docs were updated to use Node v20.
Additionally the setup steps were simplified.
The `netlify-cli` has a fixed version in the package.json and is installed via `npm install` as a dev dependency. The dev server can then be started with `npm start`. There is no need to have a global installation of the `netlify-cli` anymore.
Closes issue #642.
review them:
_See [the contribution …
> Fix local website deployment and update dev docs

- content/en/blog/2025/protect-signing-secrets-for-tekton-chains-using-confidential-computing/index.md
Related to https://tektoncd.slack.com/archives/CQYFEE00K/p1757073827770639
There's a bug in a package called `tap-spot` which is used internally by the `checklinks` plugin. When it's used to pretty print the results it fails when encountering the `:` character in the image alt text.
Replace the `:` to avoid the problem.
An alternative approach if we enounter similar issues in future, is to disable pretty printing in netlify.toml by setting `pretty = false` in the `plugins.inputs` block.
/kind misc
review them:
> Fix production build
